backend:
  name: git-gateway
  branch: main  # tu rama principal

media_folder: "images/uploads" # dónde se guardan las imágenes
public_folder: "/images/uploads"

collections:
  - name: "blog"
    label: "Blog"
    folder: "blog"
    create: true
    slug: "{{slug}}"
    fields:
      - { label: "Título", name: "title", widget: "string" }
      - { label: "Fecha", name: "date", widget: "datetime" }
      - { label: "Contenido", name: "body", widget: "markdown" }
      - { label: "Imagen destacada", name: "thumbnail", widget: "image", required: false }
